name: multiburst
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python>=3.10
  - pip
  - numpy
  - isce2>=2.6.3
  - dem_stitcher>=2.5.8
  - rasterio
  - shapely
  - jinja2
  - asf_search>=6.4.0
  - gdal
  - opencv
  - burst2safe
  - hyp3lib>=3,<4
  - s1_orbits
  - jupyterlab
  - matplotlib
  - pip:
    - hyp3-isce2@git+https://github.com/ASFHyP3/hyp3-isce2.git
